### PR TITLE
some cleanups

### PR DESCRIPTION
**Pull request by giuseppe**
it looks quite ugly to #include a .c file.  Split definitions in .h files so it is easier and much cleaner to use the library.

### CODE REVIEW

**Comment by mendsley** [comment]
Thanks for the work in cleaning up the library. I'm going to merge the license file change separately to keep this PR specific to the .h/.c cleanup

**Comment by mendsley** [comment]
Can you rebase-squash this PR onto master? That way we'll have a single commit with the .c/.h changes for the library.

**Comment by mendsley** [comment]
Can you squash these into a single commit? see: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes-optional. That way we have the entire change+fixes in a single atomic change.

**Comment by giuseppe** [comment]
sure, I have pushed only two commits now, one to split .c into .c and .h and another one to add the autoconf/automake machinery.

**Comment by mendsley** [comment]
Thanks! Everything has been tested and merged in!

**Pull request merged**
