### PR TITLE
SAIS diff algorithm; VLE algorithms; feel free to tweak, cut & modify;

### PR DESCRIPTION
**Pull request by r-lyeh**
- I have updated README with the new directives.
- I did not add another header/tag for the VLE variants (enabling VLE breaks backwards compatibility)

### CODE REVIEW

**Comment by r-lyeh** [comment]
I think that is all for now. I have had to merge on the run as my patch was based on the old version with h/c glued together : )

**Comment by CoolOppo** [comment]
It might be a good idea to allow these to be used without recompiling the program, but through a flag you can call it with from your shell.

I was looking for an explanation for the differences you've introduced, but Google didn't really turn anything relevant up, and the README doesn't really explain the differences either. I can see that you definitely put some thought into this, but the code is **really** cryptic and difficult to get a hold of without taking a while to step through a bunch of parts in my head. Are you able to explain what exactly is going on from a higher-level point of view, and the advantages and disadvantages of these new algorithms?

**Comment by r-lyeh** [comment]
@CoolOppo, yeah sorry about the terse information.
- VLE. This change is not backwards compatible. VLE option is just moving from the fixed header of the patch 3x64bit [24 bytes] to something more variable in length, say between [3 and 30]. This is a personal choice and might not be everybody's taste, though. See more info at https://github.com/r-lyeh/vle
- SAIS. This change _should_ remain backwards compatible. The SAIS option is to avoid a recursion crash as seen in #1. The patch seems to work but needs some more (real) testing, as my usage of bsdiff is quite limited.

**Comment by r-lyeh** [comment]
I could have been sending two PR instead, but got it difficult to do, as my fork was pretty outdated and diverged too much from base. Sorry about that.

**Comment by r-lyeh** [comment]
ping @mendsley

**Comment by otavio** [comment]
Has this been abandonned? if so, why?

**Pull request closed without merging**
